name: Get Qt via vcpkg
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup vcpkg
        run: |
          # Клонуємо офіційний репозиторій vcpkg
          git clone https://github.com/microsoft/vcpkg.git
          # Ініціалізуємо його
          .\vcpkg\bootstrap-vcpkg.bat
          
      - name: Install Qt6 MinGW
        run: |
          # Встановлюємо qtbase з явним зазначенням тріплету для MinGW
          .\vcpkg\vcpkg.exe install qtbase:x64-mingw-dynamic --triplet x64-mingw-dynamic
          
      - name: Archive result
        run: |
          # Пакуємо встановлені файли
          Compress-Archive -Path vcpkg\installed\x64-mingw-dynamic\* -DestinationPath Qt6_MinGW_vcpkg.zip
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qt6-MinGW-vcpkg
          path: Qt6_MinGW_vcpkg.zip
