name: Get Qt6 Binaries via Vcpkg
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install and Run vcpkg
        run: |
          # 1. Клонуємо vcpkg у поточну директорію
          git clone https://github.com/microsoft/vcpkg.git
          # 2. Запускаємо скрипт ініціалізації
          .\vcpkg\bootstrap-vcpkg.bat
          # 3. Тепер викликаємо команду встановлення
          .\vcpkg\vcpkg.exe install qt6:x64-mingw-dynamic
          
      - name: Archive vcpkg installed files
        run: |
          # Пакуємо тільки скомпільовані файли з папки installed
          Compress-Archive -Path vcpkg\installed\x64-mingw-dynamic\* -DestinationPath Qt6_vcpkg_MinGW.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qt6-vcpkg-Binaries
          path: Qt6_vcpkg_MinGW.zip
